### ISSUE TITLE
Installation problems with Expo

### ISSUE THREAD

**Issue by joeroganDOTca** [realimposter/react-native-animated-glow-wrapper#5]
Hi, I'm having some issues with the installation of all this.  I _think_ I have react-native-reanimated and @shopify/react-native-skia working because I've test very basic sample successfully.  I also _think_ my problems are related to the bable.config.js file and worklets.  I've followed the installation instructions multiple times including on a fresh newly generated Expo app, but end up with this problem every time.  Appreciate any suggestions on what to do next.

If I use the bable.config.js file I get this error and my app won't load at all:

 ERROR  ReferenceError: Property '_toString' doesn't exist, js engine: hermes
 WARN  Route "./(tabs)/SettingsScreen.tsx" is missing the required default export. Ensure a React component is exported as default.
 ERROR  ReferenceError: Property '_toString' doesn't exist, js engine: hermes
 WARN  Route "./(tabs)/index.tsx" is missing the required default export. Ensure a React component is exported as default.

Without the file it loads my screens (if I remove the AnimatedGlow component), but when trying to us AnimatedGlow it throws these errors.  I have a working GestureHandlerRootView.

[react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 WARN  [react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 WARN  [react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 ERROR  Warning: ReanimatedError: [Reanimated] Trying to convert a cyclic object to a shareable. This is not supported.

Is something wrong with this bable.config.js file? 
`
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
        'babel-preset-expo',
    ],
    plugins: [
        '@babel/plugin-proposal-export-namespace-from',
        'react-native-worklets/plugin',
    ],
  };
};
`

My current dependencies:

`
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@expo/vector-icons": "^14.1.0",
    "@react-navigation/bottom-tabs": "^7.3.10",
    "@react-navigation/elements": "^2.3.8",
    "@react-navigation/native": "^7.1.6",
    "@reduxjs/toolkit": "^2.8.2",
    "@shopify/react-native-skia": "v2.0.0-next.4",
    "expo": "~53.0.22",
    "expo-blur": "~14.1.5",
    "expo-constants": "~17.1.7",
    "expo-dev-client": "~5.2.4",
    "expo-font": "~13.3.2",
    "expo-haptics": "~14.1.4",
    "expo-image": "~2.4.0",
    "expo-linking": "~7.1.7",
    "expo-navigation-bar": "~4.2.8",
    "expo-router": "~5.1.5",
    "expo-splash-screen": "~0.30.10",
    "expo-status-bar": "~2.2.3",
    "expo-symbols": "~0.4.5",
    "expo-system-ui": "~5.0.11",
    "expo-web-browser": "~14.2.0",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-animated-glow": "^3.0.0",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-web": "^0.20.0",
    "react-native-webview": "13.13.5",
    "react-native-worklets": "^0.5.0",
    "react-native-zoom-toolkit": "^5.0.1",
    "react-redux": "^9.2.0",
    "uninstall": "^0.0.0"
  },`

**Comment by joeroganDOTca** [comment]
Thanks, have tried those steps, but now still have this error:

 WARN  [react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 WARN  [react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 WARN  [react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
 ERROR  Warning: ReanimatedError: [Reanimated] Trying to convert a cyclic object to a shareable. This is not supported.

This error is located at:

Call Stack
  RNCSafeAreaView (<anonymous>)
  RNSScreenContainer (<anonymous>)
  TabLayout(./(tabs)/_layout.tsx) (<anonymous>)
  ScreenContentWrapper (<anonymous>)
  RNSScreenStack (<anonymous>)
  RNGestureHandlerRootView (<anonymous>)
  RNCSafeAreaProvider (<anonymous>)
  App (<anonymous>)
  ErrorOverlay (<anonymous>)


I've tried to use a few samples such as https://reactnativeglow.com/tutorials/neon-text-effect but getting this error with all of them.  Screens load without errors if I comment out the AnimatedGlow component.

**Comment by realimposter** [comment]
hey @joeroganDOTca  @aledebla03 i just released version 3.0.1 that i think should fix this issue. just tested it with expo 53, Skia v2.0.0-next.4, reanimated ~3.17.4, and gesture handler ^2.28.0 and worked fine for me on ios and web.

please keep in mind v3.0.1 no longer manages the states and gestures internally, if you want hover and press states its now passed to the activeState parameter like this:

```
import React, { useState, useRef } from 'react';
import { View, Text, StyleSheet, Pressable } from 'react-native';
import AnimatedGlow, { glowPresets, type GlowEvent } from 'react-native-animated-glow';

export default function MyInteractiveButton() {
  // 1. State for the active glow effect ('default', 'hover', 'press')
  const [glowState, setGlowState] = useState<GlowEvent>('default');
  // 2. Ref to track if the cursor is currently hovering over the element
  const isHovered = useRef(false);

  return (
    <AnimatedGlow 
      preset={glowPresets.defaultRainbow}
      // 3. Pass the state to the activeState prop to control the glow
      activeState={glowState}
    >
      <Pressable
        onPressIn={() => setGlowState('press')}
        onPressOut={() => setGlowState(isHovered.current ? 'hover' : 'default')}
        onHoverIn={() => {
          isHovered.current = true;
          if (glowState !== 'press') setGlowState('hover');
        }}
        onHoverOut={() => {
          isHovered.current = false;
          if (glowState !== 'press') setGlowState('default');
        }}
      >
        <View style={styles.button}>
            <Text style={styles.buttonText}>Tap or Hover Me</Text>
        </View>
      </Pressable>
    </AnimatedGlow>
  );
}

const styles = StyleSheet.create({
    button: { paddingVertical: 15, paddingHorizontal: 30, backgroundColor: '#222' },
    buttonText: { color: 'white', fontWeight: 'bold' }
});

```

please let me know if you see any problems

**Comment by joeroganDOTca** [comment]
This is all working now, thank you so much!  I've tested it with Expo on web and Android.   Looks really nice, and I'm excited to implement this in my projects!

**Comment by XChikuX** [comment]
I'm using nitro `['react-native-worklets-core/plugin']` on `3.0.1`

And I still get 

*No known conditions for "." specifier*
